### ISSUE TITLE
Emoji picker

### ISSUE THREAD

**Issue by maddy2308** [jbw91/angular-emojione#3]

**Comment by johnbwoodruff** [comment]
I don't currently have an emoji picker component, but I'd be happy to receive any pull requests for this! As soon as I've got some spare time if I haven't gotten a pull request, I'll see if I can put something together.

**Comment by johnbwoodruff** [comment]
This repository is no longer maintained. Instead please use [ngx-joypixels](https://github.com/johnbwoodruff/ngx-joypixels). Thank you!
