### ISSUE TITLE
Serve the emoji images locally

### ISSUE THREAD

**Issue by rreddyNg** [jbw91/angular-emojione#4]
How do we point to the locally stored emoji images.

**Comment by johnbwoodruff** [comment]
Hi @ravindrap123, thanks for submitting a feature request! Could you give me some more details about what you mean by pointing to locally stored emoji images? Is this locally stored emojione images? Or custom emoji images, and you want to extend this library to support custom images?

**Comment by johnbwoodruff** [comment]
Closed due to inactivity.
