### ISSUE TITLE
version 3.1.2 has a simple error

### ISSUE THREAD

**Issue by StormFire-Technologies** [jbw91/angular-emojione#5]
There is an import error in this version that wouldn't let my app start, inside the angular-emojione.js file there are two imports referencing `emojione/index`; taking off the /index seems to fix the problem and everything is working beautifully!

**Comment by johnbwoodruff** [comment]
So sorry this issue has taken me so long, I've been quite busy the last few months! I'll try to get this taken care of as quickly as I can!

**Comment by johnbwoodruff** [comment]
This repository is no longer maintained. Instead please use [ngx-joypixels](https://github.com/johnbwoodruff/ngx-joypixels). Thank you!
