### ISSUE TITLE
Short name to unicode

### ISSUE THREAD

**Issue by swanand6300** [jbw91/angular-emojione#8]
Hi,

Thanks for this wonderful library. It is very useful.

I am facing one problem now. 

When I entered emoji using input text it renders correctly but when i unicode it to short name using `unicodeToShortname` method it displays correctly using `innerHTML` but when i edited the particular post there is no option to convert short name to unicode and it display text as "`test :blush::smile::smile::joy::smile::rofl::rofl::rofl:`". :joy:

Can you guys please help me on this .

**Comment by johnbwoodruff** [comment]
Hi @swanand6300! This repository is no longer maintained. Instead please use [ngx-joypixels](https://github.com/johnbwoodruff/ngx-joypixels). Thank you!
